### ISSUE TITLE
I would like to add a Portuguese translation

### ISSUE THREAD

**Issue by wellington-rodrigues5991** [madewithkoji/koji-i18n#3]
I am Brazilian, and Brazilians really enjoy casual games and especially with some interesting visuals. Like many that exist in Koji today, me and a friend would like to include the Portuguese translation on the site.
What is the process to do this, would include a strings.json in Portuguese?

**Comment by sthielen** [comment]
Hi Wellington!

That would be awesome. Yes, the easiest way to get started would be to make a copy of https://github.com/madewithkoji/koji-i18n/blob/master/i18n/en/strings.json in a new directory for the Portuguese language code `pt`.

Feel free to submit a pull request!

**Comment by wellington-rodrigues5991** [comment]
Great, I'll get organized to do this.
